services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19132:25575/udp"
    environment:
      EULA: "TRUE"
      VERSION: 1.21
      SERVER_NAME: "Server"
      PLAYER_IDLE_TIMEOUT: 20
      TYPE: "PAPER"
      VIEW_DISTANCE: 64
      DIFFICULTY: "hard"
      ICON: "https://djeqr6to3dedg.cloudfront.net/repo-logos/itzg/minecraft-server/live/logo-1704684813344.png"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: 10
      MAX_BUILD_HEIGHT: 400
      MAX_PLAYERS: 100
      INIT_MEMORY: 2G
      MAX_MEMORY: 8G
      ENABLE_RCON: "FALSE"
      REPLACE_ENV_VARIBLES: "TRUE"
      ENV_VARIBLE_PREFIX: "CFG_"
      MOTD: §l§cMinecraft§r
      MAX_WORLD_SIZE: 10000
      OPS: |
        Connor_33341
      #  user 2
      #  user 2
      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data